
Neos:
  Flow:
    mvc:
      routes:
        Neos.Neos:
          variables:
            defaultUriSuffix: ''
    error:
      exceptionHandler:
        renderingGroups:
          notFoundExceptions:
            options:
              variables:
                path: '404'
              viewOptions: {  }
  Fusion:
    defaultContext:
      DocsNeosIo.UserData: Neos\DocsNeosIo\Eel\Helper\UserDataHelper
  Neos:
    eventLog:
      enabled: true
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
    fusion:
      autoInclude:
        Neos.DocsNeosIo: true
    Ui:
      frontendConfiguration:
        hotkeys: ~
      resources:
        javascript:
          'Neos.DocsNeosIo:CKEConfig':
            resource: 'resource://Neos.DocsNeosIo/Public/JavaScript/CKEConfig/Plugin.js'
