Neos:
  Flow:
    i18n:
      defaultLocale: en
  Neos:
    userInterface:
      defaultLanguage: en
      translation:
        autoInclude:
          Neos.DocsNeosIo:
            - Main
            - 'NodeTypes/*'
    sitePresets:
      'default':
        uriPathSuffix: ''
    sites:
      '*':
        contentDimensions:
          # defaultDimensionSpacePoint is used for the homepage (URL /)
          defaultDimensionSpacePoint:
            language: en
          resolver:
            factoryClassName: Neos\Neos\FrontendRouting\DimensionResolution\Resolver\UriPathResolverFactory
            options:
              segments:
                -
                  dimensionIdentifier: language
                  # dimensionValue => uriPathSegment (empty uriPathSegment allowed)
                  dimensionValueMapping:
                    en: ''
  ContentRepositoryRegistry:
    contentRepositories:
      default:
        contentDimensions:
          language:
            label: Languages
            icon: icon-language
            values:
              en:
                label: English
