
Neos:
  Flow:
    mvc:
      routes:
        'Flowpack.Listable':
          variables:
            defaultUriSuffix: ''
        Neos.Neos:
          variables:
            defaultUriSuffix: ''
  Fusion:
    defaultContext:
      DocsNeosIo.UserData: Neos\DocsNeosIo\Eel\Helper\UserDataHelper
  Neos:
    eventLog:
      enabled: true
      navigateComponent:
        nodeTree:
          loadingDepth: 1
        structureTree:
          loadingDepth: 2
    fusion:
      autoInclude:
        Neos.DocsNeosIo: true
    Ui:
      frontendConfiguration:
        hotkeys: ~
      resources:
        javascript:
          'Neos.DocsNeosIo:CKEConfig':
            resource: 'resource://Neos.DocsNeosIo/Public/JavaScript/CKEConfig/Plugin.js'

    userInterface:
      navigateComponent:
        nodeTree:
          loadingDepth: 2

        structureTree:
          loadingDepth: 3
